using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;

namespace HitboxJSONRefactor
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("\t| | | This program refactors the hitbox polygons data for ShootThis-Backend\n\t| | | Written by Marin Tsanov for the ShootThis project\n\n");
            try
            {
                if (args.Length > 0)
                {
                    Dictionary<string, dynamic> jsonFile = JsonConvert.DeserializeObject<Dictionary<string, dynamic>>(File.ReadAllText(args[0]));

                    foreach (var rigidBody in jsonFile["rigidBodies"])
                    {
                        List<List<double>> polygonsList = new List<List<double>>();
                        foreach (var polygon in rigidBody.polygons)
                        {
                            List<double> polygonCoords = new List<double>();
                            foreach (var polygonCoordinates in polygon)
                            {
                                polygonCoords.Add((double)polygonCoordinates.x);
                                polygonCoords.Add(1.0 - (double)polygonCoordinates.y);
                            }
                            polygonsList.Add(polygonCoords);
                        }
                        String json = JsonConvert.SerializeObject(polygonsList);
                        File.WriteAllText(new FileInfo(args[0]).DirectoryName + "/" + rigidBody.name.ToString() + ".json", json);
                    }

                }
                else
                    throw new Exception("Invalid file supplied.");
            }
            catch(Exception e)
            {
                Console.WriteLine("An error has occurred: " + e.Message + "\n\n");
                Console.WriteLine("Please drag a valid .json file, generated by Physics Body Editor, onto the .exe.\nJSON file requirements: all default options from Physics Body Editor 2012 by Aurelien Ribon (for the grid, convex polygons) should be used, as well as origin at 0, 0 or the coordinates MUST be used.\n\nPress any key to exit.");
                Console.ReadLine();
            }
        }
    }
}
